# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: gis-datalake

plugins:
  - serverless-pseudo-parameters
  - serverless-python-requirements
  - serverless-plugin-tracing
custom:
  pythonRequirements:
    dockerizePip: true
    slim: true

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: ap-northeast-2
  profile: datalake
  # geoserver에서 해당 스택 이름으로 버킷명을 가져옴
  stackName: awskrug-handson-datalake
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
        - "s3:PutObject"
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"


# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
package:
  include:
    - util/**
  exclude:
    - data/**

#functions:
#  csv2shp:
#    handler: csv2shp.han
#      - s3:
#        bucket:
#          Fn::ImportValue: "handson-datalake-s3-name"
#        event: s3:ObjectCreated:*
#        rules:
#          - prefix: csv/
#          - suffix: .gz
#
resources:
  Resources:
    CSVResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-csv-#{AWS::AccountId}
    SHPResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-shp-#{AWS::AccountId}
    JSONResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-json-#{AWS::AccountId}
  Outputs:
     CSVS3:
       Description: "datalake csv tar.gz files bucket"
       Value:
        "Ref": CSVResource
       Export:
        Name: ${self:service}-csv
     SHPS3:
       Description: "datalake shp tar.gz files bucket"
       Value:
        "Ref": SHPResource
       Export:
        Name: ${self:service}-shp
     JSONS3:
       Description: "datalake json files bucket"
       Value:
        "Ref": JSONResource
       Export:
        Name: ${self:service}-json
